apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cv-ingress
  namespace: cv-app
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - cv.philippsaal.com
      secretName: cv-tls
  rules:
    - host: cv.philippsaal.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cv-frontend-service
                port:
                  number: 80
